### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by Hungryhumans** [adafruit/Adafruit_CircuitPython_OV7670#10]
I originally thought pull requests for questions but, after researching I found out it wasn't. Sorry for the inconvenience. https://github.community/t/how-do-you-ask-another-repository-a-question/2338
How would I wire the raspberry pi pico to the ov7670? For example, I don't know where to put most of the cables or what type of wires to use. Thank you, I apologise again for the inconvenience. Have a great day.

**Comment by jepler** [comment]
We plan that a guide will be published on learn.adafruit.com, most likely within the next month, about these camera libraries.  Among other combinations, it will show how to connect the Raspberry Pi Pico to the OV7670 camera module and use it in CircuitPython.

In the meantime, I can give you some general advice.   You will need to connect 3.3V, GND, and all the pins listed in the constructor to the camera.  You also need to add 2.2kΩ pull-ups resistors from SDA to 3.3V and from SCL to 3.3V.  In my experience, it is OK to do this with jumper wires; you may find that the M-F jumper wires [like these](https://www.adafruit.com/product/1954) work for you.  You can also use an [IDC Breakout Helper](https://www.adafruit.com/product/2101) so that you can plug the camera into a **soldered** breadboard (I don't find that this product works with a **solder-free** breadboard, the "legs" aren't long enough)

You can ask questions on the [Adafruit Forums](https://forums.adafruit.com/) or [Adafruit Discord](https://adafru.it/discord).
